name: Preview on Expo
on: [pull_request_target]
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-packager: yarn
      - run: yarn install
      - run: expo publish --release-channel=pr-${{ github.event.number }}
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: |
                App is ready for review, you can [see it here](https://exp.host/@${{ secrets.EXPO_CLI_USERNAME }}/foundry-native-ui?release-channel=pr-${{ github.event.number }}).
                ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=exp://exp.host/${{ secrets.EXPO_CLI_USERNAME }}?release-channel=pr${{ github.event.number }})
            })
